from unittest import TestCase
import os, sys
SHELL_PATH = os.path.dirname(os.path.abspath(__file__))
sys.path.append(os.path.realpath("../"))
print(sys.path)
from homepage.functions import google_search


class TestGoogleSearch(TestCase):
    def setUp(self):
        self.input_keyword1 = "doxygen"
        self.input_keyword2 = "dynamic programming"
        self.input_keyword3 = "machine learning coursera"

    def run(self, result=None):
        data1 = google_search(self.input_keyword1)
        for i in data1['items']:
            out = i['title']
        self.assertEqual('Improving Doxygen: by Daniel Hilferty Abstract: Doxygen is a ...'
                         '            Parag Chaudhuri, IIT Bombay'
                         '1.0 Generated by Doxygen 1.8.3.1'
                         'CS371p: Object-Oriented Programming'
                         'Writing and Generating Documentation'
                         'Build and Writing Guide for libstdc++ Doxygen'
                         'print-introspected-doxygen.cc'
                         'CS378: Generic Programming',
                         'Improving Doxygen: by Daniel Hilferty Abstract: Doxygen is a ...'
                         '            Parag Chaudhuri, IIT Bombay'
                         '1.0 Generated by Doxygen 1.8.3.1'
                         'CS371p: Object-Oriented Programming'
                         'Writing and Generating Documentation'
                         'Build and Writing Guide for libstdc++ Doxygen'
                         'print-introspected-doxygen.cc'
                         'CS378: Generic Programming'
                          )